### ISSUE TITLE
Link to author

### ISSUE THREAD

**Issue by BogdanMakarchuk** [xXNiceAssasinl0/MaskShop-UI#1]
Please provide a link to the post with the plugin, please, because this is a violation of the rules

link https://vk.com/plugplus?w=wall-121838923_12619

**Comment by xXNiceAssasinl0** [comment]
Done

**Comment by FreakingDev** [comment]
@BogdanMakarchuk  so it's you who stole codes and claimed it as yours. Wow -.-

**Comment by BogdanMakarchuk** [comment]
@FreakingDev the code was overwritten
