### ISSUE TITLE
Want to clear something

### ISSUE THREAD

**Issue by FreakingDev** [xXNiceAssasinl0/MaskShop-UI#3]
You copy the code from plugplus that copy my code so that i thought you're copying my code. And by the way i have proof that it's the same as i mine coz you use the same libraries format as mine, and for you're information some of that is not needed

**Comment by xXNiceAssasinl0** [comment]
I didn’t copy anything I downloaded plugin and make it in English.

**Comment by xXNiceAssasinl0** [comment]
I have nothing to do with this please ask plugplus about this issue not me thank you for your time.

**Comment by FreakingDev** [comment]
It's the same tho. You should not modifying this plugin. If you want to be a dev. Make your own code, and start from the scratch :D That will help you to understand programming.

**Comment by xXNiceAssasinl0** [comment]
-_- my friend told me to make it English for his server so stop hating on me.

**Comment by FreakingDev** [comment]
Im not. I just want to make it clear.

**Comment by xXNiceAssasinl0** [comment]
Well I am sorry dude I already upload this video in YouTube

**Comment by xXNiceAssasinl0** [comment]
+ Plugins was already modify don’t believe go to their link and do whatever you want sorry can’t delete this I am really sorry. I used to watch your plugins video lol xd

**Comment by FreakingDev** [comment]
I have nothing to do with that. Next time don't copy code from plugplus coz they just stole it from another dev. If you have questions or anything you can contact me on discord and join my dev team.

**Comment by xXNiceAssasinl0** [comment]
FreakingDev, You blocked me on discord lol cause you think I was jerk to you

**Comment by FreakingDev** [comment]
No im not O.O I just unfriend some

**Comment by xXNiceAssasinl0** [comment]
Oh let me see than.

**Comment by xXNiceAssasinl0** [comment]
Sent friend request

**Comment by BogdanMakarchuk** [comment]
@FreakingDev the code has been completely rewritten, so you have no relation to this plugin already ..

**Comment by xXNiceAssasinl0** [comment]
Thank you @BogdanMakarchuk for help
